For #11529: history management improvements
GPLgithub/tk-multi-breakdown2 pull request #3
Opened 2023-09-27 22:47 UTC by ksallee

- Similar to what's done in https://github.com/GPLgithub/tk-multi-loader2/pull/2, add a `published_file_matching_fields` setting
- Here it also controls the published_files_mapping we do in the `file_item_model`. This is to ensure that the latest Published File is properly retrieved.
- IMHO, the logic of the get_published_files standard hook should also be based on the setting, but for now I did that in `tk-config-gplstudio` (PR to follow)

2023-09-28 10:00 UTC, gplsteph requested changes
A better name for the setting should be found. And I suspect clashes between different entity types can happen in the internal dictionary?

2023-09-28 10:00 UTC, gplsteph commented on info.yml
> +    published_file_matching_fields:
Please find a better name.

2023-09-28 10:00 UTC, gplsteph commented on python/tk_multi_breakdown2/file_history_model.py
> +            filters.append([field, "is", sg_data[field]])
Any worry that this would be break with other fields than simple fields?

2023-09-28 10:00 UTC, gplsteph commented on python/tk_multi_breakdown2/file_item_model.py
> +                field_value = field_value.get("id")
Not sure this can actually happen, but here it seems you wouldn't be able to make a difference between Shot 1234 and Asset 1234?

2023-09-28 17:05 UTC, ksallee commented on python/tk_multi_breakdown2/file_history_model.py
> +            filters.append([field, "is", sg_data[field]])
you have any example in mind?

2023-09-29 08:58 UTC, gplsteph requested changes
Not approving because I think a bug was introduced.
Please address as needed, if changes are little, no need for another CR.

2023-09-29 08:58 UTC, gplsteph commented on hooks/get_published_files.py
> +            self.logger.debug("Retrieved %d Published Files" % len(result))
Isn't that a bg task id?

2023-09-29 08:58 UTC, gplsteph commented on hooks/get_published_files.py
> +        self.logger.debug("Found latest Published File %s" % result)
Same comment: in one case it's SG records, in the other it's a bg task id, I think?

2023-09-29 08:58 UTC, gplsteph commented on info.yml
> +                     the app will look for Published Files with the same project, task, entity, name and
Please remove the "By default" comment, or add some code to do that if the setting is empty.

2023-09-29 08:58 UTC, gplsteph commented on info.yml
> +          [ "project", "task", "entity", "name", "published_file_type" ]
You can move your comment about the default value here.

2023-09-29 08:58 UTC, gplsteph commented on python/tk_multi_breakdown2/file_history_model.py
> +        # based on the publish_file_matching_fields setting.
Please update your comment.

2023-09-29 08:58 UTC, gplsteph commented on python/tk_multi_breakdown2/file_history_model.py
> +            filters.append([field, "is", sg_data[field]])
Don't know, since I asked the question...

2023-09-29 08:58 UTC, gplsteph commented on python/tk_multi_breakdown2/file_item_model.py
> +                if index == len(group_by_fields) - 1:
We can't use a defaultdict because of that, right? May be add a comment mentioning that?

2023-09-29 16:16 UTC, merged