For #12520: integrate changes from shotgunsoftware
GPLgithub/tk-multi-breakdown2 pull request #5
Opened 2024-01-09 01:00 UTC by ksallee

The biggest change that kind of clashed with what we have changed is the addition of the `published_file_filters` setting. Since we added some `get_published_files_for_items_data` in our manager/hook setup, I mimicked the changes that were done to `get_published_files_for_items` (i.e. adding a filters param to the hook method and setting it to the user setting when called)

Other than that, all the changes come from shotgunsoftware. I tested as much as I could and it does not seem to break.
We have a base `get_published_files.py` hook in our `tk-config-gplstudio` that also needs a slight update to add the `filters` param.

2024-01-09 08:00 UTC, gplsteph requested changes
Not sure I commented on what was needed, but I spotted a potential bug.

2024-01-09 08:00 UTC, gplsteph commented on hooks/get_published_files.py
> +        filters = filters or []
Hmm, aren't we modifying the passed `filters`?

2024-01-09 23:58 UTC, ksallee commented on hooks/get_published_files.py
> +        filters = filters or []
fixed

2024-01-10 08:29 UTC, gplsteph approved these changes
Looks good, just some suggestions for some params

2024-01-10 08:29 UTC, gplsteph commented on hooks/get_published_files.py
> +        :param filters: A list of filters to use when querying SG.
```suggestion
        :param filters: An optional list of filters to use when querying SG.
```

2024-01-10 08:29 UTC, gplsteph commented on hooks/get_published_files.py
> +        :param filters: A list of filters to use when querying SG.
```suggestion
        :param filters: An optional list of filters to use when querying SG.
```

2024-01-10 16:02 UTC, merged